title: Security
type: documentation
changelogURL:
items:
  - date: 2021-11-05
    summary: Added security updates section.
    summaryAdditional:
    isBreaking:
    affectsAccessibility:
    affectsAssets:
    affectsGuidance: true
    affectsJavascript:
    affectsMarkup:
    affectsStyles:
    githubPr: 1304
    githubRepo: uswds-site
    versionUswds:
