version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  codecov: codecov/codecov@1.0.2
  a11ywatch: a11ywatch/a11ywatch@dev:alpha

executors:
  my-executor:
    docker:
      - image: cimg/ruby:3.0.4-browsers

jobs:
  web:
    machine:
      image: ubuntu-2004:current
  install_ruby_deps:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache
      - run:
          name: Install ruby dependencies
          command: |
            gem update --system
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Install scss_lint
          command: gem install scss_lint
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/project
          paths:
            - "vendor/bundle"
  install_node_deps:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache
      - run:
          name: Build USWDS components if needed
          command: npm run build:uswds
      - run:
          name: Build site assets
          command: npm run build:all-assets
      - run:
          name: Build static site
          command: |
            bundle config set --local path '~/project/vendor/bundle'
            bundle exec jekyll build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "_site"
            - "assets"
            - "node_modules"
  test_build:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run rspec
          command: |
            bundle config set --local path '~/project/vendor/bundle'
            bundle exec rspec
      - run:
          name: Run HTML proofer
          command: npm run proof
      - snyk/scan:
          organization: uswds

workflows:
  circle-uswds-site:
    jobs:
      - install_ruby_deps
      - install_node_deps
      - build:
          requires:
            - install_ruby_deps
            - install_node_deps
      - test_build:
          requires:
            - build
      - a11ywatch/scan:
          to: "https://a11ywatch.com"
          requires:
            - build

